### ISSUE TITLE
Crashes with no exception

### ISSUE THREAD

**Issue by hegenafre** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#185]
## Expected Behavior
Return or raise an exception

## Actual Behavior
No return and no exception and simply returns to main activity.
However, works fine on some Android phones but not on others.

## Steps to Reproduce the Problem

  1. Follow all documentation and try on different Android phones
  1.
  1.

## Specifications

  - NuGet package version: 2.1.34
  - Platform(s): Xamarin, Android 9, Api 28

**Comment by vividos** [comment]
@sriharrsha This seems not to be the same issue as the original poster had, since he had no exception and no call stack. You may want to update to the latest beta NuGet package, where a permission problem was fixed. Might also fix your problem!

**Comment by sriharrsha** [comment]
I am already on Latest beta package

**Comment by zwrtron** [comment]
The problem is still present in 2.1.41 (latest stable). Any solution for this?

**Comment by vividos** [comment]
You could always try out the sample project in this repository and see if there's some crash reported, or if the debugger stops somewhere.

**Comment by jfversluis** [comment]
Closing this since this project will retire, please check out [Xamarin.Essentials](https://github.com/xamarin/Essentials/tree/main/Xamarin.Essentials/FilePicker) which now has a FilePicker based on this one.
