### ISSUE TITLE
System.NotImplementedException: This functionality is not implemented in the portable version of this assembly

### ISSUE THREAD

**Issue by simyco** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#19]
Hi, good work for this plugin!

> System.NotImplementedException: This functionality is not implemented in the portable version of this assembly. You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.

I've just the title problem when running ios (android no problem).
I'm running xamarin forms and installing nuget package in PCL and in ios project.
I've also tried to add directly reference to monotouch10 dll with no success.
What can i do?
thanks in advance

**Comment by jfversluis** [comment]
Thanks! Hm, this is the second time I hear this. Will need to check this out!

**Comment by simyco** [comment]
great! if it could be useful i'm using netstandard

**Comment by jfversluis** [comment]
That is probably the problem, there is no netstandard support right now :)

**Comment by xacte-richard** [comment]
I have the same problem here, can't get it to work on iOS. I don't use netstandard.

**Comment by jfversluis** [comment]
@simyco I don't quite understand. But if you're offering you could implement the netstandard support then I'll gladly accept a PR for that.

**Comment by simyco** [comment]
i'll try in the next days

**Comment by JayMansel** [comment]
Just to add, I'm getting the same issue and NOT using .netstandard (using .Net framework 4.5.1).

**Comment by afk013** [comment]
Not sure if this helps. I am using .netstandard. I tried building a nuget using #20 and iOS still had the same exception but then I added direct references to the #20 projects in my solution and it appears to be working. I haven't done exhaustive tests as I have only started using the plugin today but if I come across anything else I'll let you know.

**Comment by jfversluis** [comment]
@afk013 could you give it a shot with 2.0.2-beta? Maybe something gets cross with the NuGet package references. If it still doesn't work OOTB I will dive into it.

**Comment by Denaindra** [comment]
is it case of not enable iCould Access in the provision profiles ... ?

**Comment by jfversluis** [comment]
Tried to fix it with adjusting the nuspec file. Could you verify this is fixed in 2.0.3-beta?

**Comment by JayMansel** [comment]
Still getting this issue. I've updated to 2.0.2-beta, done a clean build, and confirmed iCloud permissions are set up correctly.

**Comment by jfversluis** [comment]
Whoops I said 2.0.3 but meant 2.0.8 https://www.nuget.org/packages/Xamarin.Plugin.FilePicker/2.0.8-beta

**Comment by JayMansel** [comment]
Confirmed fixed in latest build :)

**Comment by jfversluis** [comment]
Sweet! Thanks!
